# Site settings
title: Tung Huynh
email: tunghuynh314@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/example" # the subpath of your site, e.g. /blog/
url: "http://magiciiboy.github.io" # the base hostname & protocol for your site
twitter_username: tunghuynh314
github_username:  magiciiboy

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext

# Theme
theme: minima
