# Site settings
title: Tung Huynh
email: 
description: > # this means to ignore newlines until "baseurl:"
  I am a software engineer and a researcher. My interests includes the Mind and the Universe.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://magiciiboy.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  magiciiboy
linkedin_username: huynhtung

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext

# Theme
theme: minima
